### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by mssgill**
Including the first one word change and then correcting the later CModel Fluxes sentence according to JimB's prescription for it.

### CODE REVIEW

**Comment by mssgill** [comment]
hi @jdswinbank - i've tried putting the corrections in as i think @TallJimbo suggested, hopefully doing this right.

**Comment by jdswinbank** [comment]
Thank you!

It'd probably be a good idea to close down the [old PR](https://github.com/lsst-dm/dmtn-023/pull/2) since it's replaced by this one.

Unfortunately, I'm not sure your changes quite agree with [Jim's comment](https://github.com/lsst-dm/dmtn-023/pull/2#discussion_r70701712). I think the correct solution is more like https://github.com/lsst-dm/dmtn-023/commit/f1f34be84250e5c6ff13458026daac8cc9933d05. Can you check if you agree, and, if so, I'll go ahead and merge that?

**Comment by mssgill** [comment]
@jdswinbank -- ok, i just checked, and that version you pointed to seems fully fine (i had taken a marked up version and removed a few words Jim had struck out, and it did seem to make logical sense, but clearly wasn't exactly still what he meant, sorry about that, still learning on this front), and is good to merge now.

I also note you closed the old PR already, so we're cool on that front too, and we can close this also, after the merge, yes?

Seems like a plan!

**Comment by jdswinbank** [comment]
Ok -- #4 merged as agreed. Shutting this down. Thanks @mssgill!

**Pull request closed without merging**
